### PR TITLE
Refactor 2: Son of Refactor

### PR DESCRIPTION
**Pull request by mysterycommand**
## This is a Refactor of [the Refactor](https://github.com/johnnybenson/sassr/pull/7)
All the same major changes apply, this just has a (much) tidier commit history, and fewer dev dependencies (no Browserify, no Jsdom). If this looks good I'll update the README to include usage of the require hook.

**Aside:**
> One other value to having a `.test` suffix on tests is that you can glob them into Mocha more easily, the test script is now `mocha 'test/**/*.test.js'` which avoids picking up the `test/utils.js` file (or any other non-test scripts) … which is nice.

@kmck @johnnybenson

### CODE REVIEW

**Comment by shz** [comment]
LGTM :+1:

**Comment by mysterycommand** [comment]
Four tests are skipped right now because I'm not sure what to do. They are [here](https://github.com/mysterycommand/sassr/blob/mysterycommand/refactor/2/test/sassr.test.js#L70-L86) and [here](https://github.com/mysterycommand/sassr/blob/mysterycommand/refactor/2/test/sassr.test.js#L110-L126). Basically, the stream-returning functions just emit an error if they run into bad CSS, where as the transform functions will actually return an "error module". The old stream function pushed the error module into the stream, but then emitted the error, which I think will just kill the stream? I'm not super sure, but that's what it looks like in my testing. So, emit the error, or just pass an "error module" through?

**Comment by shz** [comment]
I'm not sure how to deal with that using `through2`, but for a regular stream the "correct" behavior would be to do a `stream.emit('error', err)` sort of deal.  In the case of browserify this will break the build completely, which I think is what you want?

Picking between behaviors, I'd rather have my build break on bad (S)CSS than accidentally ship bad stuff into prod.  Is the error module approach ever desirable?

**Comment by mysterycommand** [comment]
I think the error module approach could be handy in development, with the require hook? I'm not sure what the debugging story would be like for a test that required a module a that required some bad [S]CSS … would it be better to throw an error in the test, or `console.error` with a message.

Somewhat confusingly, the existing behavior is to `stream.push` the module **AND THEN** `stream.emit` the error. I guess, for now I'll just keep the existing behavior for the stream functions, and return the error module from the transform functions. We can come decide whether the stream functions should not push the error module, and if we want to get rid of the error module all together in a later PR?

**Comment by shz** [comment]
As long as that later PR actually happens, I'm good with it.  Plus, you've already got my +1, so it's all up to you and @johnnybenson / @kmck at this point.

**Comment by mysterycommand** [comment]
I just ran a local experiment to see what kind of coverage we've got.

```
=============================== Coverage summary ===============================
Statements   : 100% ( 69/69 )
Branches     : 100% ( 12/12 )
Functions    : 100% ( 12/12 )
Lines        : 100% ( 69/69 )
================================================================================
```

Looks pretty good, but digging into the generated reports it's not covering any of the `utils` tests.

This issue: https://github.com/gotwarlost/istanbul/issues/293
This PR: https://github.com/gotwarlost/istanbul/pull/294

… look promising. If we ever get there. :)

**Comment by kmck** [comment]
i dig it :+1:

**Comment by kmck** [comment]
yeah, there "error module" stuff is weird. seems like it makes browserify hang (even on the current npm version). let's nuke that separately.

**Pull request merged**
